### ISSUE TITLE
FFT optimizations

### ISSUE THREAD

**Issue by Chillee** [dacin21/dacin21_codebook#1]
Considering how much you seemed to like optimizing that HLPP implementation :^), I thought I'd let you know that your FFT implementation has 2 major optimizations that can be made.

1. Your root access is cache-inefficient (you're jumping all over the place). It's possible to calculate your roots in an order s.t. you can iterate through the roots in a cache-efficient way.

2. There's an optimization called FFT 2-in-1, where you put one polynomial in the real part, one polynomial in the complex part, and cut down your total FFT's from 3 (2 forward and 1 reverse) to 2 (1 forward, 1 reverse).

You can view more detailed descriptions of these optimizations here: http://neerc.ifmo.ru/trains/toulouse/2017/fft2.pdf

Currently, your FFT is 3-4x slower than mine due to missing these optimizations. See https://ideone.com/c5TWCe

You can see my implementation of these optimizations here: https://gist.github.com/Chillee/4982ba0840745f63f3771bd84f280557#file-ntt-cpp

**Comment by dacin21** [comment]
Thanks for you comment. I assume the implementation you looked at was [nt/FFT_double.cpp](https://github.com/dacin21/dacin21_codebook/blob/06eebe5129177aba2b6aa9083ba2bb5626304308/nt/FFT_double.cpp). That implementation is indeed quite slow and I stopped using it more than a year ago.

The implementation I'm currently using is [nt/polynomials_2.0.cpp](https://github.com/dacin21/dacin21_codebook/blob/06eebe5129177aba2b6aa9083ba2bb5626304308/nt/polynomials_2.0.cpp). It uses both optimization you mentioned and runs almost as fast as you code (equally fast if you replace `ll` by `int32_t`). See https://ideone.com/oaMnHH

The one optimization I couldn't get to work yet was vectorization. (But vectorization seems to only be possible on some judges.)

**Comment by Chillee** [comment]
Seems like you're right! My bad - I didn't check the other files after I saw the FFT one. The reason I was looking for your FFT code on the first place was the rankings on SPOJ POLYMUL.

Thanks for the explanation!
